project_id = "nkxdmmzrnflpxgetixev"

[functions.movie-chat]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.process-movie-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false
